export const teamList = {
    Barcelona: {
        id: '001',
        region: 'Europe',
        country: 'Spain',
        name: 'Barcelona',
        nationalLeagueTitles: 27,
        nationalCupTitles: 31,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 5,
        clubWorldCupTitles: 3
    },
    RealMadrid: {
        id: '002',
        region: 'Europe',
        country: 'Spain',
        name: 'Real Madrid',
        nationalLeagueTitles: 35,
        nationalCupTitles: 20,
        uelOrSudamericanaTitles: 2,
        uclOrLibertadoresTitles: 14,
        clubWorldCupTitles: 8
    },
    Valencia: {
        id: '003',
        region: 'Europe',
        country: 'Spain',
        name: 'Valencia',
        nationalLeagueTitles: 6,
        nationalCupTitles: 8,
        uelOrSudamericanaTitles: 1,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    AtléticoMadrid: {
        id: '004',
        region: 'Europe',
        country: 'Spain',
        name: 'Atlético Madrid',
        nationalLeagueTitles: 11,
        nationalCupTitles: 10,
        uelOrSudamericanaTitles: 3,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    AthleticBilbao: {
        id: '005',
        region: 'Europe',
        country: 'Spain',
        name: 'Athletic Bilbao',
        nationalLeagueTitles: 8,
        nationalCupTitles: 23,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    Sevilla: {
        id: '006',
        region: 'Europe',
        country: 'Spain',
        name: 'Sevilla',
        nationalLeagueTitles: 1,
        nationalCupTitles: 5,
        uelOrSudamericanaTitles: 7,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    RealBetis: {
        id: '007',
        region: 'Europe',
        country: 'Spain',
        name: 'Real Betis',
        nationalLeagueTitles: 1,
        nationalCupTitles: 3,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    DeportivoLaCoruña: {
        id: '008',
        region: 'Europe',
        country: 'Spain',
        name: 'Deportivo La Coruña',
        nationalLeagueTitles: 1,
        nationalCupTitles: 2,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    RealSociedad: {
        id: '009',
        region: 'Europe',
        country: 'Spain',
        name: 'Real Sociedad',
        nationalLeagueTitles: 2,
        nationalCupTitles: 2,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    Juventus: {
        id: '010',
        region: 'Europe',
        country: 'Italy',
        name: 'Juventus',
        nationalLeagueTitles: 36,
        nationalCupTitles: 14,
        uelOrSudamericanaTitles: 3,
        uclOrLibertadoresTitles: 2,
        clubWorldCupTitles: 0
    },
    Milan: {
        id: '011',
        region: 'Europe',
        country: 'Italy',
        name: 'Milan',
        nationalLeagueTitles: 19,
        nationalCupTitles: 5,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 7,
        clubWorldCupTitles: 0
    },
    InterMilan: {
        id: '012',
        region: 'Europe',
        country: 'Italy',
        name: 'Inter Milan',
        nationalLeagueTitles: 19,
        nationalCupTitles: 9,
        uelOrSudamericanaTitles: 3,
        uclOrLibertadoresTitles: 3,
        clubWorldCupTitles: 1
    },
    Napoli: {
        id: '013',
        region: 'Europe',
        country: 'Italy',
        name: 'Napoli',
        nationalLeagueTitles: 3,
        nationalCupTitles: 6,
        uelOrSudamericanaTitles: 1,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    Roma: {
        id: '014',
        region: 'Europe',
        country: 'Italy',
        name: 'Roma',
        nationalLeagueTitles: 3,
        nationalCupTitles: 9,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    Lazio: {
        id: '015',
        region: 'Europe',
        country: 'Italy',
        name: 'Lazio',
        nationalLeagueTitles: 2,
        nationalCupTitles: 7,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    Genoa: {
        id: '016',
        region: 'Europe',
        country: 'Italy',
        name: 'Genoa',
        nationalLeagueTitles: 9,
        nationalCupTitles: 1,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    Torino: {
        id: '017',
        region: 'Europe',
        country: 'Italy',
        name: 'Torino',
        nationalLeagueTitles: 7,
        nationalCupTitles: 5,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    Bologna: {
        id: '018',
        region: 'Europe',
        country: 'Italy',
        name: 'Bologna',
        nationalLeagueTitles: 7,
        nationalCupTitles: 2,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    Fiorentina: {
        id: '019',
        region: 'Europe',
        country: 'Italy',
        name: 'Fiorentina',
        nationalLeagueTitles: 2,
        nationalCupTitles: 6,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    ProVercelli: {
        id: '020',
        region: 'Europe',
        country: 'Italy',
        name: 'Pro Vercelli',
        nationalLeagueTitles: 7,
        nationalCupTitles: 0,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    BayernMunich: {
        id: '021',
        region: 'Europe',
        country: 'Germany',
        name: 'Bayern Munich',
        nationalLeagueTitles: 33,
        nationalCupTitles: 20,
        uelOrSudamericanaTitles: 1,
        uclOrLibertadoresTitles: 6,
        clubWorldCupTitles: 2
    },
    BorussiaDortmund: {
        id: '022',
        region: 'Europe',
        country: 'Germany',
        name: 'Borussia Dortmund',
        nationalLeagueTitles: 8,
        nationalCupTitles: 5,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 1,
        clubWorldCupTitles: 0
    },
    Nuremberg: {
        id: '023',
        region: 'Europe',
        country: 'Germany',
        name: 'Nuremberg',
        nationalLeagueTitles: 9,
        nationalCupTitles: 4,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    Schalke04: {
        id: '024',
        region: 'Europe',
        country: 'Germany',
        name: 'Schalke 04',
        nationalLeagueTitles: 7,
        nationalCupTitles: 5,
        uelOrSudamericanaTitles: 1,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    Hamburger: {
        id: '025',
        region: 'Europe',
        country: 'Germany',
        name: 'Hamburger',
        nationalLeagueTitles: 6,
        nationalCupTitles: 3,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 1,
        clubWorldCupTitles: 0
    },
    Stuttgart: {
        id: '026',
        region: 'Europe',
        country: 'Germany',
        name: 'Stuttgart',
        nationalLeagueTitles: 5,
        nationalCupTitles: 3,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    BorussiaMonchengladbach: {
        id: '027',
        region: 'Europe',
        country: 'Germany',
        name: 'Borussia Monchengladbach',
        nationalLeagueTitles: 5,
        nationalCupTitles: 3,
        uelOrSudamericanaTitles: 2,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    WerderBremen: {
        id: '028',
        region: 'Europe',
        country: 'Germany',
        name: 'Werder Bremen',
        nationalLeagueTitles: 4,
        nationalCupTitles: 6,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 2
    },
    Kaiserslautern: {
        id: '029',
        region: 'Europe',
        country: 'Germany',
        name: 'Kaiserslautern',
        nationalLeagueTitles: 4,
        nationalCupTitles: 2,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    Koln: {
        id: '030',
        region: 'Europe',
        country: 'Germany',
        name: 'Koln',
        nationalLeagueTitles: 3,
        nationalCupTitles: 4,
        uelOrSudamericanaTitles: 0,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    EintrachtFrankfurt: {
        id: '031',
        region: 'Europe',
        country: 'Germany',
        name: 'Eintracht Frankfurt',
        nationalLeagueTitles: 1,
        nationalCupTitles: 5,
        uelOrSudamericanaTitles: 2,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    },
    BayerLeverkusen: {
        id: '032',
        region: 'Europe',
        country: 'Germany',
        name: 'Bayer Leverkusen',
        nationalLeagueTitles: 0,
        nationalCupTitles: 1,
        uelOrSudamericanaTitles: 1,
        uclOrLibertadoresTitles: 0,
        clubWorldCupTitles: 0
    }
}